"""empty message

Revision ID: 1233ab8b238
Revises: 1406d4e2825
Create Date: 2015-03-16 16:31:07.569693

"""

# revision identifiers, used by Alembic.
revision = '1233ab8b238'
down_revision = '1406d4e2825'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bet', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bet', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###
