"""empty message

Revision ID: 2d9719aacd1
Revises: 4a998bdd515
Create Date: 2015-03-16 13:02:04.911986

"""

# revision identifiers, used by Alembic.
revision = '2d9719aacd1'
down_revision = '4a998bdd515'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bet_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bets')
    ### end Alembic commands ###
