"""empty message

Revision ID: 4cadf0d29e8
Revises: 4f56c1d460
Create Date: 2015-03-16 14:48:23.933581

"""

# revision identifiers, used by Alembic.
revision = '4cadf0d29e8'
down_revision = '4f56c1d460'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('challenger', sa.Integer(), nullable=True))
    op.add_column('bets', sa.Column('creator', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bets', 'creator')
    op.drop_column('bets', 'challenger')
    ### end Alembic commands ###
