"""empty message

Revision ID: 4f56c1d460
Revises: 2d9719aacd1
Create Date: 2015-03-16 14:17:18.528148

"""

# revision identifiers, used by Alembic.
revision = '4f56c1d460'
down_revision = '2d9719aacd1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('date', sa.String(length=255), nullable=True))
    op.add_column('bets', sa.Column('location', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bets', 'location')
    op.drop_column('bets', 'date')
    ### end Alembic commands ###
